---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "rc1a-3u06v0pniep7bp60.mdb.yandexcloud.net"
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "db_user"
            - name: MYSQL_ROOT_PASSWORD
              value: "p@$$w0rD"